### PR TITLE
Cockpit 254

### PR DESCRIPTION
**Pull request by garrett**
Preview: https://garrett.github.io/cockpit-project.github.io/blog/cockpit-254.html

### CODE REVIEW

**Comment by garrett** [comment]
It's still a few days early, so I ran this in preview mode to include all merged and possible (unmerged) release-notes PRs, and to get the links to each PR inline. :wink:

**Comment by garrett** [comment]
Removed release-notes tags from items from last week's release and regenerated the preview (in preview mode)

**Comment by garrett** [comment]
Regenerated, dropped preview mode

**Comment by garrett** [comment]
Waiting for https://github.com/cockpit-project/cockpit/pull/16402 to land. Once it does, we need new screenshots for https://github.com/cockpit-project/cockpit/pull/16260.

**Comment by garrett** [comment]
Regenerated with the login info.

I guess we need to manually move the overview above users; the features are related.

**Comment by garrett** [comment]
Manually added summary and reordered sections.

TODO: We need official release links when they're available.

**Comment by marusak** [comment]
Updated links

**Review by martinpitt — APPROVED** [review]
Danke!

**Pull request merged**
