### PR TITLE
fix install command on Debian

### PR DESCRIPTION
**Pull request by Smana**

### CODE REVIEW

**Comment by larsu** [comment]
I intentionally chose `apt` here because that seems to be the preferred tool these days and it's what the debian administrator's handbook uses in its examples [1].  

Why did you change it?

[1] https://debian-handbook.info/browse/stable/sect.apt-get.html

**Comment by Smana** [comment]
Yes sorry, i'm not up to date :p

**Comment by stefwalter** [comment]
So does 'apt' work on all Debians that Cockpit is targetting? If so, I'm certainly not against changing it back.

**Comment by larsu** [comment]
Nah, it doesn't matter. I was just curious if there was a specific reason for the change.

**Pull request merged**
