### PR TITLE
fixed RHEL branding to follow the Red Hat brand guidelines. Fixes #22

### LINKED ISSUE #22: misuse of Red Hat Shadowman logo
In the [try it out](http://cockpit-project.org/running.html) page, the Shadowman logo is used incorrectly. There are two issues:

1. Shadowman is used without the "Red Hat" wordmark. From [brand.redhat.com](http://brand.redhat.com/logos/shadowman/):

> Our corporate logo is Shadowman and the accompanying “Red Hat” wordmark.
> We never say never, but Red Hat very seldom approves the use of the Shadowman icon alone, without the wordmark. When we do, there is always a very good reason, considered and sanctioned at the highest levels.

2. Shadowman is used to represent RHEL Atomic Host, a product of Red Hat. This is also incorrect. Again, details here: [brand.redhat.com](http://brand.redhat.com/logos/productlogos/):

**EDIT:** I'm far from an expert in this area, which is why I don't have any helpful suggestions. You should probably contact the marketing people. Some of them might be behind [this contact form](http://brand.redhat.com/feedback/).

### PR DESCRIPTION
**Pull request by andreasn**

### CODE REVIEW

**Comment by stefwalter** [comment]
@lathan Could you review this change? That would be much appreciated.

**Comment by stefwalter** [comment]
Fixes #22

**Comment by andreasn** [comment]
It looks like this in action screenshot from 2015-03-27 12 18 46

**Comment by andreasn** [comment]
Also centered the logo per Libby Levi's feedback over e-mail.

**Comment by andreasn** [comment]
So now it looks like this:
screenshot from 2015-03-27 17 56 57

**Comment by lathan** [comment]
hey @stefwalter I don't have anything to add. Seems you guys have it covered. :)

**Comment by lathan** [comment]
:+1:

**Pull request merged**
