### PR TITLE
Cockpit 290

### PR DESCRIPTION
**Pull request by garrett**
Preview: https://garrett.github.io/cockpit-project.github.io/blog/cockpit-290.html

### CODE REVIEW

**Comment by garrett** [comment]
As usual, this is just the initial preview run. I haven't removed tags yet or revised text. I'll run it again tomorrow with a few updates.

**Comment by martinpitt** [comment]
Uh, this doesn't include https://github.com/cockpit-project/cockpit-machines/pull/857 for some reason. Let's regenerate in prod mode.

**Comment by martinpitt** [comment]
Now the text has all items that I'd like to document, and I added the bodhi URLs. @garrett , can you please do a round of English editing? Thank you!

**Comment by garrett** [comment]
OK, I'll regenerate in production now.

**Review by allisonkarlitskaya — APPROVED** [review]
Looks good to my eye :)

**Pull request merged**
