### PR TITLE
style: Increase contrast and realign blue to PF4

### PR DESCRIPTION
**Pull request by garrett**

### CODE REVIEW

**Comment by garrett** [comment]
The shade of blue changes, but most importantly, I've fixed the contrast across the site.

**Comment by garrett** [comment]
Live preview @ https://garrett.github.io/cockpit-project.github.io/

Screenshots:

Screenshot_2019-11-13 Running Cockpit — Cockpit Project

Screenshot_2019-11-13 Blog posts — Cockpit Project

**Comment by andreasn** [comment]
Sure, works for me.

**Comment by martinpitt** [comment]
Well done @ all hail to our new blue IBM overlords! :bowing_man:

**Pull request merged**
