### PR TITLE
search: Use DuckDuckGo when JS is not enabled

### LINKED ISSUE #178: search: fall back to external search engine when JS is not enabled
The search engine should fall back to an external search engine when JavaScript is disabled. For the sake of no-tracking, I suggest DuckDuckGo.

### PR DESCRIPTION
**Pull request by garrett**
Fixes #178

### CODE REVIEW

**Review by martinpitt — COMMENTED** [review]
How is that only used without js? Is there some `<noscript>` somewhere that doesn't appear in the diff?

**Comment by garrett** [comment]
It's "progressive enhancement": It's a standard form that submits a query to DuckDuckGo. HTML forms work without any JavaScript. :wink:

The JS already has `preventDefault`, so it works as before when you have JavaScript enabled.

**Comment by garrett** [comment]
Before this change, it didn't send the form to anywhere, so it posted it back on the same page. But as we have a static site, it didn't do anything.

I should've fixed this long ago... especially as it's so simple. Whoops. Better late than never.

**Review by martinpitt — APPROVED** [review]
Ack, thanks!

**Pull request merged**
