### PR TITLE
Cockpit 294

### PR DESCRIPTION
**Pull request by jelly**

### CODE REVIEW

**Comment by jelly** [comment]
@martinpitt

**Comment by jelly** [comment]
https://jelly.github.io/cockpit-project.github.io/blog/cockpit-294.html

**Comment by martinpitt** [comment]
@jelly FTR, it's not worth releasing podman and machines this round. There's nothing user-visible.

**Comment by martinpitt** [comment]
Blocked, still waiting for the flatpak beta release.

**Comment by martinpitt** [comment]
@jelly PR relnote updated, unblocked. Can you please regenerate? Also, bodhi is ready: https://bodhi.fedoraproject.org/updates/?packages=cockpit

**Review by martinpitt — APPROVED** [review]
Let's land this!

**Pull request merged**
