### PR TITLE
Cockpit 229

### PR DESCRIPTION
**Pull request by mvollmer**
Rendered: https://mvollmer.github.io/cockpit-project.github.io/blog/cockpit-229.html

### CODE REVIEW

**Comment by garrett** [comment]
Wow. Looks good! I have a few very minor tweaks I'd like to make.

**Comment by garrett** [comment]
I've updated the screenshot (removed color fringing, fixed the corners, lessened the shadow, and optimized for file size), removed its border (which is meant to be used for partial screenshots), and adjusted the text with a lot of little edits.

If you're happy with all these changes, please squash it all together before (or during) landing this PR.

**Review by garrett — APPROVED** [review]
LGTMN (after all my changes) :+1:

**Comment by mvollmer** [comment]
@garrett, thanks! I'll squash the commits.

**Pull request merged**
