### PR TITLE
Cockpit 162

### PR DESCRIPTION
**Pull request by martinpitt**
Rendered preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-162.html

### CODE REVIEW

**Comment by martinpitt** [comment]
@garrett: As our resident native English speaker who is not on vacation, can you please have a look?

**Comment by garrett** [comment]
@martinpitt: Sure thing! Looking now.

**Comment by garrett** [comment]
Uh... GitHub did some weird stuff and closed this PR. Sorry.

**Comment by martinpitt** [comment]
@garrett: I did a force-push to add a Closes # (so it's easier to merge), now I can reopen it.

**Comment by garrett** [comment]
I guess I had permissions to mess up your master branch, but not to fix it. Changes are all preserved @ https://github.com/garrett/cockpit-project.github.io/tree/martinpitt-master

You should be able to `git reset --hard ` your branch to my branch.

Comparison view @martinpitt 
https://github.com/cockpit-project/cockpit-project.github.io/compare/master...garrett:martinpitt-master?expand=1

**Comment by martinpitt** [comment]
Force-pushed again to incorporate @garrett 's feedback, thanks!

**Pull request merged**
