### PR TITLE
Use possessive in ideals.md's title

### PR DESCRIPTION
**Pull request by NateEag**
It's more direct and compact.

### CODE REVIEW

**Comment by martinpitt** [comment]
Hm, at least as a non-native speaker I find the original one more pleasant to read -- nicer rhythm and looks better as a title. But I don't have a strong opinion, so I'm ok with landing this.

**Comment by NateEag** [comment]
Interesting, @martinpitt - as a native American English speaker, I filed the PR precisely because the "Ideals Of Cockpit" phrasing felt awkward and clunky to me.

Thanks for the feedback!

**Review by martinpitt — APPROVED** [review]
Ack -- I trust your judgement as native speaker :grin:

**Comment by NateEag** [comment]
Thanks!

**Pull request merged**
