### PR TITLE
Cockpit 295

### PR DESCRIPTION
**Pull request by garrett**
Preview: https://garrett.github.io/cockpit-project.github.io/blog/cockpit-295.html

### CODE REVIEW

**Comment by allisonkarlitskaya** [comment]
The .png files are text files which contain the text "Not Found".

**Comment by allisonkarlitskaya** [comment]
I have a fixed up version of this, but I can't seem to push it :(

**Comment by martinpitt** [comment]
No idea, I'm afraid. GitHub says "Maintainers are allowed to edit this pull request. ". If that doesn't work, then I propose to close this one and you open a new PR from your branch @allisonkarlitskaya ?

**Comment by allisonkarlitskaya** [comment]
> No idea, I'm afraid. GitHub says "Maintainers are allowed to edit this pull request. ". If that doesn't work, then I propose to close this one and you open a new PR from your branch @allisonkarlitskaya ?

→ #644

**Pull request closed without merging**
