### PR TITLE
Cockpit 262

### PR DESCRIPTION
**Pull request by garrett**
Preview: https://garrett.github.io/cockpit-project.github.io/blog/cockpit-262.html

### CODE REVIEW

**Comment by martinpitt** [comment]
@garrett : I did a first round of editing on the pending release notes. If you have a quiet moment until tomorrow, I'd appreciate a re-review / editing in the ones which already landed or are fairly close:

 - https://github.com/cockpit-project/cockpit/pull/16890
 - https://github.com/cockpit-project/cockpit/pull/16885
 - https://github.com/cockpit-project/cockpit/pull/16884

Thanks!

**Comment by garrett** [comment]
Regenerated the release notes as-is; I'll review the PRs in a bit.

**Comment by martinpitt** [comment]
I did a force-push to swap the order of the sections and fill in some details.

**Comment by martinpitt** [comment]
Release finished, I added bodhi URLs.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
