### PR TITLE
External documentation

### PR DESCRIPTION
**Pull request by garrett**
Currently, there are a bunch of useful docs that are not included on the project website (and, as such, are not indexed so that they can be searched).

I've written a script (which can be run periodically, and would be ideal to be run by a bot) and made a few commits to fix this visibility issue:

- added a script to fetch the latest versions of selected documents from the Cockpit git source and project wiki
- committed current version of docs
- pointed the contribute nav link to the included document

A nice side-effect of these changes is that we can have all the navigation at the top of the page stay within the website as well.

### CODE REVIEW

**Comment by garrett** [comment]
I've dealt with `git submodules` and `git subtree` before, and they're both a mess. This is a better alternative, especially since we only want a select few documents, and they need to be slightly rewritten (with frontmatter, and updated links) anyway.

**Comment by garrett** [comment]
I merged in this PR as well as #102 into master on my fork so it can be previewed.

Nav link to contribution goes to http://garrettlesage.com/cockpit-project.github.io/external/wiki/Contributing.html

The top pages on the search http://garrettlesage.com/cockpit-project.github.io/search.html#/external are all "new" pages brought in by these changes.

**Comment by garrett** [comment]
(Added `{{ site.baseurl }}` to script & doc so sub-sites, such as fork previews, are properly supported & force-pushed to this branch.)

**Comment by garrett** [comment]
Do you know if it's possible to add the script `_scripts/update-external-docs.rb` to the bot so that it can run it periodically and the commit the results? Or add it to some commit hook, or something similar?

**Comment by garrett** [comment]
Also, is this a good selection of documents to include from the git repo & wiki? 

https://github.com/garrett/cockpit-project.github.io/blob/266a5486a6c606f7ba9a79f9801b84f621900348/_scripts/update-external-docs.rb#L5-L17

Or should we include additional documents? (Those can be added later too.)

**Comment by andreasn** [comment]
I like the idea of not suddenly ending up on GitHub while clicking around in the navigation.

This layout looks a  bit off.
screenshot from 2017-10-10 15-22-43

**Comment by garrett** [comment]
Yeah, that page is just funky. I think I'll remove it and instead rewrite that particular link to land on GitHub.

**Comment by garrett** [comment]
(Ideally, we would have a better page and rewrite the link to that instead... probably even in the origin doc.)

**Comment by garrett** [comment]
OK, dropped page from being included and changed the link to point to the GitHub page, at least for now.

**Comment by garrett** [comment]
Fixes #90 by-the-way. :wink:

**Comment by garrett** [comment]
Committing this, as it fixes issues and people seem to be happy with it.

**Pull request merged**
