### PR TITLE
Cockpit 164

### PR DESCRIPTION
**Pull request by martinpitt**
Rendered preview: https://martinpitt.github.io/cockpit-project.github.io/blog/cockpit-164.html

### CODE REVIEW

**Comment by garrett** [comment]
I wonder if it makes sense to do section-related items like "pagename: feature update":

- Storage: usability improvements
- System: show available package updates and missing subscription
- Logs: changed severities
- Machines: added error notifications
- Fixed inconsistent tooltips on system overview and navigation
- Accessibility improvements
- Reloading the browser now reloads Cockpit package manifests

Is it too inconsistent with the rest of the headings?

**Comment by martinpitt** [comment]
@garrett, not too late;  I'm happy to move to this schema, if we do this consistently. Only for the "short" release news on the tag/package changelogs, or also for the long release notes?

**Comment by garrett** [comment]
Yeah, I'm not sure. It's just an idea, if we want to prioritize the sections. I'm happy to reword otherwise.

**Comment by martinpitt** [comment]
@garret: I do like this style, too. I adjusted this PR accordingly, and also used it for the actual tag: https://github.com/cockpit-project/cockpit/releases/164

**Comment by garrett** [comment]
You misspelled my name again. :disappointed: 

GitHub really needs to fix their autocompletion and give preference to people:
1. on the issue
2. in your teams
3. who you're following
4. who you've interacted with
5. the rest

In that order.

**Comment by martinpitt** [comment]
Updated again according to @garrett's feedback, thank you!

**Pull request merged**
