### PR TITLE
screenshots: Add back scroll wheel support

### PR DESCRIPTION
**Pull request by garrett**
When I removed touch support in #398, I accidentally removed scroll wheel support too. Adding it back.

### CODE REVIEW

**Comment by garrett** [comment]
It should be available on https://garrett.github.io/cockpit-project.github.io/ in a few minutes.

**Comment by garrett** [comment]
Whoops, I goofed up. Fixing now.

**Comment by garrett** [comment]
Fixed.

After copy/pasting the original code, ESLint complained about the event as it was a deprecated API (which worked). Now it's using an event passed by the listener.

**Review by allisonkarlitskaya — APPROVED** [review]
wfm

**Pull request merged**
