### PR TITLE
Fonts and colors

### LINKED ISSUE #256: Update website with new fonts (and refreshed colors?)
Similar to https://github.com/cockpit-project/cockpit/pull/11987 & #255, the website should probably have new fonts too. And probably should use refreshed colors.

But it shouldn't be as big of a deal at all. :grin:

### PR DESCRIPTION
**Pull request by garrett**
- Change the fonts to RedHatDisplay and RedHatText
- Update the header color gradient to use PF4 blues
- Fix fonts in the guide

Fixes #256

### CODE REVIEW

**Comment by garrett** [comment]
Oh, I included the gems update. I should split that into another PR.

**Comment by garrett** [comment]
I guess this should land right around the time of our release? :man_shrugging:

**Comment by garrett** [comment]
Preview @ https://garrett.github.io/cockpit-project.github.io/

**Comment by martinpitt** [comment]
Nice, thank you! Yes, let's land this tomorrow.

Also, we need to update our screenshots again :-)

**Comment by garrett** [comment]
Screenshots issue is #255. :wink: (But I think we need everyone's help on this.)

**Pull request merged**
