### PR TITLE
Optimize images and switch to webp for the front page

### PR DESCRIPTION
**Pull request by garrett**
This cuts down the front page load by half and only loads images on demand. It should improve load times for mobile, especially.

(Screenshots on blog posts are still fine as PNG, as long as we optimize them. The cumulative effect of multiple screenshots adds up quite a bit on the front page.)

### CODE REVIEW

**Comment by jelly** [comment]
Is there a deployed version to look around?

**Comment by garrett** [comment]
> Is there a deployed version to look around?

No, I have the FAQ deployed at the moment. I could merge the two branches though.

**Comment by garrett** [comment]
I've merged the PRs on my main branch for previewing; the webp changes can be see at https://garrett.github.io/cockpit-project.github.io/

**Review by martinpitt — APPROVED** [review]
Very cool, thank you! The size reduction is quite impressive. Let's land this quickly, to de-conflict it with your FAQ PR #585

**Pull request merged**
