### PR TITLE
Cockpit 253

### PR DESCRIPTION
**Pull request by garrett**
Preview: https://garrett.github.io/cockpit-project.github.io/blog/cockpit-253.html

### CODE REVIEW

**Comment by garrett** [comment]
I've published this in preview mode, so it considers both closed _and open_ PRs and shows the URLs for each PR inline in the blog post.

(When we re-run the release notes script with default options, it won't include the open PRs or additional information inline.)

**Comment by martinpitt** [comment]
@garrett , @KKoukiou : I rewrote/reformatted the relnote in https://github.com/cockpit-project/cockpit/pull/16290 . This should fix the formatting in the [preview](https://garrett.github.io/cockpit-project.github.io/blog/cockpit-253.html). Please adjust for language as you see fit, of course.

**Comment by garrett** [comment]
Rebased, squashed, pushed to preview site.

**Comment by martinpitt** [comment]
LGTM, thanks! There was a hiccup in koji, which caused our workflow to get stuck. I cancelled it, and finished the rest manually. bodhi URLs are now available for all of cockpit{,-podman,-machines}, please update the URLs.

**Comment by martinpitt** [comment]
As discussed in the meeting, let's remove podman -- this isn't ready for release yet, due to some UI workflow regressions.

**Comment by garrett** [comment]
Removed podman from the release notes, squashed, force-pushed.

**Comment by martinpitt** [comment]
Added the cockpit bodhi URLs.

**Review by martinpitt — APPROVED** [review]

**Pull request merged**
