### PR TITLE
restyle website

### LINKED ISSUE #184: Redesign website
Here's a suggestion to start working on a redesign:
redesigned website mockup

Related, for the content area: #182 (messaging improvements)

### PR DESCRIPTION
**Pull request by garrett**
fixes #184

### CODE REVIEW

**Comment by garrett** [comment]
This is a work-in-progress. Do not merge until @andreasn, @martinpitt, and I are all back from vacation (meaning: September). The three of us as well as the rest of the team should follow this PR and provide feedback.

Also, I need to remove some extra files, as I'm playing around with our font selection and we have too many included now. (Not a huge deal though; they're only downloaded if needed.)

**Comment by garrett** [comment]
I have a live preview on my fork @ https://garrett.github.io/cockpit-project.github.io/

**Comment by garrett** [comment]
Ideally, we'll also land improvements for the content around the same timeframe as the restyle. See #182 for that. (This yet-to-be-done new content needs a new design too — but that's mainly the content area of the front page.)

**Comment by andreasn** [comment]
Could maybe also bind the content together like this?
screenshot from 2018-09-05 16-27-46

But mostly nitpicking from me. Should be good to go as is.

**Comment by garrett** [comment]
Oh, I fixed that header issue already. But it's back. I guess I undid my fix somewhere. :cry:

FWIW; the dashed line was echoing the element from behind the planes when the website is longer and connects the headings with the paragraphs like arrows (without arrowheads).

**Comment by andreasn** [comment]
> FWIW; the dashed line was echoing the element from behind the planes when the website is longer and connects the headings with the paragraphs like arrows (without arrowheads).

Yeah, I'm good with either solution. So keeping it as is makes sense.

**Comment by garrett** [comment]
I had some nice feedback via Aral on Mastodon about:
- the navigation getting lost in mobile mode, as it's visually grouped with intro area on the front page
- dashed lines under the headers becoming noise on mobile

To address these, I'm thinking of extending the dark background from the logo to the navigation items too, in mobile mode only. And also dropping the dashed lines in mobile mode as well.

**Comment by garrett** [comment]
Additionally, I talked with @larskarlitski this morning and we agreed having the latest version on the page, possibly as a badge which links to the latest release blog post makes sense. (This could be done in a follow-up PR too.)

**Comment by larskarlitski** [comment]
As I said before, I really like the new look.

I only noticed two little issues while testing it:
1. The slant is not shown on Safari. It falls back to a straight line. I think that's fine, but I thought I'd let you know.
2. The menu looks weird on mobile, because it is to the right of the cockpit logo. With the old style, the menu flowed under the logo on small widths.

> possibly as a badge which links to the latest release blog post makes sense. (This could be done in a follow-up PR too.)

Yeah, this makes sense as a follow-up.

Thanks!

**Comment by garrett** [comment]
> The slant is not shown on Safari. It falls back to a straight line. I think that's fine, but I thought I'd let you know.

Same in Epiphany (GNOME Web). It seems WebKit doesn't support clip-path yet. I'll have to see if a `-webkit-` prefix works around this.

> The menu looks weird on mobile, because it is to the right of the cockpit logo. With the old style, the menu flowed under the logo on small widths.

It's under the logo in Firefox. I seem to have broken Chrome (and I guess WebKit too, according to your report).

Additionally, the new badge seems to go out of bounds on Chrome.

I'll have to fix these three issues on Monday.

**Comment by garrett** [comment]
Fixed the Chrome layout. It seems Chrome and Edge do not like `calc()` in `@media` queries.

**Comment by garrett** [comment]
(Still need to cherry-pick the fixes into the PRs... will do in a short bit.)

**Pull request merged**
